//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.8 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.05.26 at 07:37:35 PM AEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://example.com/hello", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.example.helloservice.schema;
